import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../../components/layout';
import CampCosmosHomePageImage from '../../../public/images/camp-cosmos-home-page.svg'

const Home = () => (
  <Layout>
    <Head>
      <title>Camp Cosmos</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/camp-cosmos-logo.svg" />
    </Head>
    <div className="home">
      <div className="home--img">
        <Image
          src={CampCosmosHomePageImage}
          priority={true}
          alt="Camp Cosmos home page image"
        />
      </div>
    </div>
  </Layout>
);

export default Home;