import React from 'react';
import Head from 'next/head';
import Layout from '../../components/layout';

const Home = () => (
  <Layout>
    <Head>
      <title>Camp Cosmos</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="home">
      <div className="home--img">
        <img src="images/camp-cosmos-home-page.svg" alt="Camp Cosmos home page image" />
      </div>
    </div>
  </Layout>
);

export default Home;
// export default function Home() {
//   return (
//     <div class="py-12 bg-white">
//       <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
//         <div class="lg:text-center">
//           <h2 class="text-base text-red-500 font-semibold">Good Morning</h2>
//           <p class="mt-2 text-blue-800 text-3xl leading-8 font-extrabold tracking-tight sm:text-4xl">Welcome to KindaCode.com</p>
//         </div>

//         <div class="mt-10 space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10">
//           <div
//             className="bg-amber-500 cursor-pointer text-white p-4 rounded-md text-center shadow-xl">
//             <div className="mt-2 font-bold">John Doe</div>
//             <div className="font-light">Some description</div>
//           </div>

//           <div
//             className="bg-red-500 cursor-pointer text-white p-4 rounded-md text-center shadow-xl">
//             <div className="mt-2 font-bold">John Doe</div>
//             <div className="font-light">Some description</div>
//           </div>

//           <div
//             className="bg-green-500 cursor-pointer text-white p-4 rounded-md text-center shadow-xl">
//             <div className="mt-2 font-bold">John Doe</div>
//             <div className="font-light">Some description</div>
//           </div>

//           <div
//             className="bg-purple-500 cursor-pointer text-white p-4 rounded-md text-center shadow-xl">
//             <div className="mt-2 font-bold">John Doe</div>
//             <div className="font-light">Some description</div>
//           </div>
//         </div>


//       </div>
//     </div>
//   )
// }