import React from 'react';
import Head from 'next/head'
import Layout from '../components/layout';
import styles from '../styles/home.module.scss';

const HomePage = () => (
  <Layout>
    <Head>
      <title>Camp Cosmos</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.home}>
      <div>
        <img src="images/camp-cosmos-homepage.svg" alt="Camp Cosmos home page image" />
      </div>
    </div>
  </Layout>
);

export default HomePage;
