import React from 'react';
import Link from 'next/link'
import Head from 'next/head'

const HomePage = () => (
  <div>
    <Head>
      <title>Camp Cosmos</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>
      <Link href="/galaxy">
        <a>To Galaxy page!</a>
      </Link>
    </h1>
  </div>
);

export default HomePage;
